#
# Home:                 /
# About Page:           /about/
# Archive Page:         /archive/
# Pagination:           /page/N/
# Post:                 /post/post-slug/
# RSS Feed:             /feed.xml
#

# Basics
# --------------------

name:                   kremalicious
description:            'Blog of designer & developer Matthias Kretschmann'
url:                    http://kremalicious.com
author:                 Matthias Kretschmann
email:                  m@kretschmann.io


# Urls
# --------------------

permalink:              /:title
relative_permalinks:    true
paginate:               15
paginate_path:          "/page/:num"
category_dir:           "/"
category_title_prefix:  ""


# Content Parsing
# --------------------

future:                 false
markdown:               redcarpet
pygments:               true

redcarpet:
  extensions:           ['autolink', 'smart', 'hard_wrap']


# Generator
# --------------------

source:                 ./_src
destination:            ./_site
exclude:                ['less', 'app.js']
keep_files:             ['media', 'gen']


# jekyll-picture-tag
# --------------------

picture:
  source: "_media"
  output: "media/gen"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      attr:
        itemprop: "image"
      source_medium:
        media: "(min-width: 35.556em)"
        width: "640"
      source_small:
        media: "(min-width: 26.667em)"
        width: "480"
      source_default:
        width: "320"
    sticky:
      ppi: [1, 2]
      attr:
        class: "sticky-image"
        itemprop: "image"
      source_default:
        width: "190"